name: CI for React App

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Node.js version
        run: node -v

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Print installed packages
        run: npm list

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
